using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace GearSDK_CSharpDLL.Gear_Objects
{
    public class Gear_<MY_OBJECT>_csharp
    {
        #region Attributes

        int id;
        string name;
        string pin;
        int value;

        #endregion

        #region Constructors

        public Gear_<MY_OBJECT>_csharp()
        {
            
        }

        public Gear_<MY_OBJECT>_csharp(int id, string name, string pin, int value)
        {
            this.id = id;
            this.name = name;
            this.pin = pin;
            this.value = value;
        }

        #endregion

        #region Gets and Sets
        
        public int Id { get => id; }
        public string Name { get => name; }
        public string Pin { get => pin; }
        public int Value { get => value; set => this.value = value; }

        #endregion

    }
}

namespace Json.<MY_OBJECT>
{
	/*
	CREATE ALL THIS CLASSES WITH THE SITE: http://json2csharp.com
	Or made your on classes with the names bellow
	
	- USING THE SITE -
	Put the header json on this site, and re-name the RootObject to Root_Header
	Change the <MY_OBJECT> class generated by site to Header
	Put the data json on this same site, and re-name the RootObject to Root_Data
	------------------
	*/
    public class Header
    {
        public string name { get; set; }
        public string pin { get; set; }
        public int value { get; set; }
    }

    public class Root_Header
    {
        public Header myObject { get; set; }
    }

    public class Data
    {
        public string name { get; set; }
        public int value { get; set; }
    }

    public class Root_Data
    {
        public Data myObject { get; set; }
    }
}
